### ISSUE TITLE
Huisnummer toevoegen aan locatie 

### ISSUE THREAD

**Issue by bartdegraeve** [digipolisantwerp/location-picker-leaflet_widget_angular#1]
Wanneer ik een straat manueel ingeef en selecteer en hierachter nog een huisnummer typ, geeft de kaart het volgende weer 'geen resultaat gevonden'

Deze vraag is ifv de nieuwe meldingstool AMAP

https://jira.antwerpen.be/browse/GIS-52

**Comment by jsebrech** [comment]
Is een issue in de onderliggende location picker. Zal daar gefixt worden.

https://github.com/digipolisantwerp/location-picker_widget_angular/issues/3

**Comment by jsebrech** [comment]
Opgelost in v2.1.1 van location-picker service @acpaas-ui-widgets/nodejs-location-picker.
