### ISSUE TITLE
breedte kaart

### ISSUE THREAD

**Issue by bartdegraeve** [digipolisantwerp/location-picker-leaflet_widget_angular#2]
Vooral op smart phones valt de kaart nogal breed uit waardoor mensen met dikkere vingers een probleem ondervinden om makkelijk door te scrollen op het scherm, vermits ze moeilijk op de dunnen strook naast de kaart kunnen scrollen. Men verzet vooral de kaart ipv te scrollen op het device.

Het probleem blijkt te zijn dat de breedte wordt bepaald door de gebruikte leaftlet, waaraan sommige zaken, zoals breedte en default zoom level na locatie, niet kunnen worden aangepast.

Een mogelijkheid zou zijn volgens Jeroen Brock is om de leaflet zelf te vervangen door een andere, waaraan wel het een en ander kan worden aangepast. 

Kan dat eens bekeken worden. Jeroen kan eventueel de aanpassing wel doorvoeren (natuurlijk is dat wel een change request die we zullen moeten betalen dan).

**Comment by jsebrech** [comment]
Ik zal dit oppikken.

**Comment by jsebrech** [comment]
Hoe / waar kan ik dit reproduceren?

**Comment by jsebrech** [comment]
Antwoord: reproduceerbaar op https://amap-a.antwerpen.be

**Comment by jsebrech** [comment]
De aui-leaflet tag heeft width: 100%; wat wil zeggen dat die automatisch de breedte van de container neemt. Wil je die een andere breedte geven moet je dus de container een andere breedte geven. Zelf zie ik niet meteen welke ingreep er specifiek nodig is om dit flexibeler te maken, maar technische details of PR's zijn altijd welkom.

**Comment by TriangleJuice** [comment]
Hey @bartdegraeve 
De reden dat de kaart te veel tegen de kant komt, is een foutieve implementatie van het grid (ik zie zelfs dat de devs hun eigen classes gebruikt hebben). Best is dat ze onze container classes gebruiken en dat ze ze als volgt hanteren:

```
<main class="u-wrapper">
	<div class="u-container">
		...
	</div>
</main>
```

Ik ga dan ook dit ticket sluiten, omdat het geen defect van de location picker is. Voor meer info verwijs ik u graag door naar één van onze Slack kanalen.
