### ISSUE TITLE
location should not be filled out initially when not specified

### ISSUE THREAD

**Issue by jsebrech** [digipolisantwerp/location-picker-leaflet_widget_angular#7]
When loading the widget it automatically puts the street name that is at the center of the map in the input field. This field should work in the other direction: there should be a way to specify the initial location (location object) which fills out the input field with a default value, and that in turn navigates the map to the appropriate coordinate (also specified in the location object). If no location is specified the map picks the center of antwerp, but the location input field remains empty.

This allows applications that use this widget to specify an initial location and get sane behavior, while still getting a good default view in case there is no default location and the user must still choose one.

**Comment by lievenvg** [comment]
Added information based on conversation with topic starter.
> I can imagine two ways of fixing the issue: (1) the dumb way, by having the user able to pass a complete location object and just using that as-is, which puts the onus on the user to figure out how to get the full location object, or (2) the smarter way of having the developer pass in a location id, and having a way in the BFF to fetch the full location object based on that id (including coordinates). Both approaches have a benefit, the first one doesn't need an additional API call which improves performance, the second one is simpler to use for the developer.

**Comment by lievenvg** [comment]
Requested enhancement added with PR #14 and available in `@acpaas-ui-widgets/ngx-location-picker-leaflet@3.0.0`.
